import Head from "next/head";
import Layout from './components/common/Layout'

const AdminDashboard = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <body style={{ backgroundColor: "#1E1E30", 'height': '100%' }} />
      </Head>

      <Layout>
        {children}
      </Layout>

    </div>
  );
};

export default AdminDashboard;
