import Head from "next/head";
import Layout from '../../components/common/Layout'

const AdminDashboard = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {children}
      </Layout>

    </div>
  );
};

export default AdminDashboard;
