import Head from "next/head";
import '../components/common/ClientHeader/ClientHeader'
import Image from "next/image";
import ClientHeader from "../components/common/ClientHeader/ClientHeader";
import ClientContainer from "../components/common/ClientContainer/ClientContainer";
import ClientHome from "../components/ClientHome/ClientHome";

const Home = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <ClientContainer>
          <ClientHome />
        </ClientContainer>
      </>
    </div>
  );
};

export default Home;
