import Head from "next/head";
import {useRouter} from "next/router";
export default function RegisterPage() {
const {push,query} = useRouter()
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="sm:mr-32px sm:ml-32px">
        <nav className="items-center rounded-4 mb-20px sm:mt-30  flex bg-clientRed justify-between">
          <div className="text-white ml-3 font-mukta text-25 sm:text-35 font-extrabold my-13px sm:ml-9 sm:my-9">
            Foody.
          </div>
          <img
            src="/countryFlags/uk.svg"
            className="cursor-pointer sm:w-41 w-33 mr-3 sm:mr-6"
            alt=""
          />
        </nav>
        <div className="flex-col mx-3 my-3 flex sm:flex-row sm:mx-0 ">
          <div className="bg-clientRed py-3 sm:pt-24 sm:pl-40 sm:mr-10 sm:pb-48 sm:pr-15 px-10 rounded-4 mb-11">
            <img
              alt=""
              src="/loginImages/register.svg"
              className="w-216 sm:w-507"
            />
          </div>
          <div className="">
            <div className="flex ml-20 flex-row sm:gap-x-16 sm:ml-174px sm:mb-18 sm:mt-105px gap-x-9 mb-15">
              <p onClick={()=>push('/login')} className="cursor-pointer text-clientGray sm:text-3xl text-xl font-normal">
                Login
              </p>
              <p className="text-clientRed sm:text-3xl text-xl font-medium sm:mr-44">
                Register
              </p>
            </div>
            <div className="">
              <div className="mb-26px">
                <p className=" font-body text-lg sm:mb-10px sm:text-xl text-grayInput mb-4 font-medium">
                  Full Name
                </p>
                <input
                  placeholder="Full name"
                  className="pl-3 sm:h-68px bg-clientInput w-full h-14 text-lg font-medium"
                />
              </div>
              <div className="mb-26px">
                <p className=" font-body text-lg sm:mb-10px  text-grayInput sm:text-xl mb-4 font-medium">
                  Username
                </p>
                <input
                  placeholder="Username"
                  className="pl-3 sm:h-68px bg-clientInput w-full h-14 text-lg font-medium"
                />
              </div>
              <div className="mb-26px">
                <p className=" font-body text-lg sm:mb-10px  text-grayInput sm:text-xl mb-4 font-medium">
                  Email
                </p>
                <input
                  type="email"
                  placeholder="Email"
                  className=" pl-3 sm:h-68px bg-clientInput w-full h-14 text-lg font-medium"
                />
              </div>
              <div className="mb-26px">
                <p className=" font-body sm:mb-10px text-lg text-grayInput sm:text-xl mb-4 font-medium">
                  Password
                </p>
                <input
                  type="password"
                  placeholder="Password"
                  className="pl-3 sm:mb-72px sm:h-68px bg-clientInput w-full h-14 text-lg font-medium"
                />
              </div>
            </div>
            <button className="w-full text-22 text-white sm:h-68px bg-clientRed font-medium h-14">
              Register
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
